# Generated by Django 5.1.6 on 2025-04-27 20:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('folder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='videos/<django.db.models.fields.CharField>/')),
                ('transcript', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_annotated', models.BooleanField(default=False)),
                ('annotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EditedVideo',
            fields=[
                ('id', models.AutoField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('folder_name', models.CharField(blank=True, max_length=255, null=True)),
                ('file', models.FileField(upload_to='edited_videos/<django.db.models.fields.CharField>/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('transcript', models.TextField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('is_annotated', models.BooleanField(default=False)),
                ('annotated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('original_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edited_versions', to='main.video')),
            ],
        ),
    ]
