# Generated by Django 5.1.6 on 2025-03-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
