# Generated by Django 5.1.6 on 2025-04-27 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_editedvideo_id_alter_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='merged_video_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
