# Generated by Django 5.1.6 on 2025-05-30 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_video_merged_video_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='automated_transcript',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='potential_problem',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='sibi_sentence',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='video',
            name='transcript_alignment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='video',
            name='file',
            field=models.FileField(upload_to='videos/%Y/%m/%d/'),
        ),
        migrations.DeleteModel(
            name='EditedVideo',
        ),
    ]
