# Generated by Django 5.1.6 on 2025-12-22 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_video_automated_transcript_video_potential_problem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='video_n_duration',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
